openapi: 3.0.1
info:
  title: DefaultResourceAPI
  description: API Definition of DefaultResourceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/default
paths:
  /get:
    get:
      responses:
        default:
          description: Default response
  /post:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /put:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /delete:
    delete:
      responses:
        default:
          description: Default response
